In [1]:
import numpy as np
import pandas as pd

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

creating a dataframe

In [2]:
data = {
    'Name': ['John','Anna','Peter','Leo'],
    'Age': [28,34,29,42],
    'City': ['New York','Paris','Berlin','London'],
    'Salary': [65000,70000,62000,85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3    Leo   42    London   85000

In [3]:
data_list = [
    ['john',28,'newyork',65000],
    ['anna',34,'paris',70000],
    ['peter',29,'berlin',62000],
    ['leo',42,'london',85000]
]
df2 =pd.DataFrame(data_list)

columns=["Name","Age","City","Salary"]  # if u want to use list then u have to intialize header aor this names by ur own (manually)
df2 =pd.DataFrame(data_list,columns = columns)
df2

    Name  Age     City  Salary
0   john   28  newyork   65000
1   anna   34    paris   70000
2  peter   29   berlin   62000
3    leo   42   london   85000

Selection and indexing of columns

In [4]:
df2

    Name  Age     City  Salary
0   john   28  newyork   65000
1   anna   34    paris   70000
2  peter   29   berlin   62000
3    leo   42   london   85000

In [5]:
df2['Name']

0     john
1     anna
2    peter
3      leo
Name: Name, dtype: object

In [6]:
df2[['Name','City']]

    Name     City
0   john  newyork
1   anna    paris
2  peter   berlin
3    leo   london

Creating a new columns

In [7]:
df2['Designation']= ['Doctor','Engineer','IAS officer','dentist']

In [8]:
df2

    Name  Age     City  Salary  Designation
0   john   28  newyork   65000       Doctor
1   anna   34    paris   70000     Engineer
2  peter   29   berlin   62000  IAS officer
3    leo   42   london   85000      dentist

removing columns

In [9]:
#if u only write this statement it only show the copy of dattaframe wher that element show deleted but in irl i does not even deleted from main memory only showing a copy of dataframe
df2.drop('Designation',axis=1)

    Name  Age     City  Salary
0   john   28  newyork   65000
1   anna   34    paris   70000
2  peter   29   berlin   62000
3    leo   42   london   85000

In [10]:
# inplace keyword use to delte data from the main memory 
df2.drop('Designation',axis=1,inplace = True)

In [11]:
df2.drop(['City','Salary'],axis=1)

    Name  Age
0   john   28
1   anna   34
2  peter   29
3    leo   42

In [12]:
df2

    Name  Age     City  Salary
0   john   28  newyork   65000
1   anna   34    paris   70000
2  peter   29   berlin   62000
3    leo   42   london   85000

removing a row

In [13]:
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   anna   34   paris   70000
2  peter   29  berlin   62000
3    leo   42  london   85000

selecting rows

In [14]:
df2

    Name  Age     City  Salary
0   john   28  newyork   65000
1   anna   34    paris   70000
2  peter   29   berlin   62000
3    leo   42   london   85000

In [15]:
df2.loc[0]

Name         john
Age            28
City      newyork
Salary      65000
Name: 0, dtype: object

In [16]:
df2.loc[[0,1]]

   Name  Age     City  Salary
0  john   28  newyork   65000
1  anna   34    paris   70000

In [17]:
df2.iloc[3]

Name         leo
Age           42
City      london
Salary     85000
Name: 3, dtype: object

Selecting subsets of rows and columns

In [18]:
df.loc[[0,1]][['City','Salary']]   #row and columns

       City  Salary
0  New York   65000
1     Paris   70000

In [19]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3    Leo   42

conditional statements

In [20]:
df2

    Name  Age     City  Salary
0   john   28  newyork   65000
1   anna   34    paris   70000
2  peter   29   berlin   62000
3    leo   42   london   85000

In [21]:
# i only want to see those people whose age is abbove 30

df2[df2['Age']>30]

   Name  Age    City  Salary
1  anna   34   paris   70000
3   leo   42  london   85000

In [22]:
# i only want to see those people whose age is abbove 30 and their city must be paris

df2[(df2["Age"] > 30) & (df2["City"] == "paris")]

   Name  Age   City  Salary
1  anna   34  paris   70000