In [1]:
import numpy as np 
import pandas as pd

Merging 2 dataframes

In [8]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['John','Anna','Peter','Leo','Bob'],
    'department': ['HR','IT','Finance','IT','HR']
})


salaries = pd.DataFrame({
    'employee_id': [1,2,3,4,6],
    'salary': [60000,80000,65000,70000,90000],
    'bonus': [5000,10000,7000,8500,12000]
})

In [10]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4    Leo         IT
4            5    Bob         HR

In [9]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            4   70000   8500
4            6   90000  12000

In [ ]:
# for merging u always have that one base coulmn like employee_id w2hich is common in both

pd.merge(employees,salaries, on='employee_id',how='inner')

# We use how='inner' to keep only those rows where the employee_id exists in both DataFrames — basically the common intersection.
# Inner join returns only matching records from both tables based on the key column.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            4    Leo         IT   70000   8500

In [17]:
# Outer join ka matlab hai dono DataFrames ke sabhi rows ko include karna, chahe match ho ya na ho. Agar kisi ek DataFrame me value missing ho, to Pandas us jagah NaN fill kar deta hai.

pd.merge(employees,salaries, on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4    Leo         IT  70000.0   8500.0
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  90000.0  12000.0

In [ ]:
pd.merge(employees,salaries, on='employee_id',how='left')
# it shows employee_id on the bases employees

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4    Leo         IT  70000.0   8500.0
4            5    Bob         HR      NaN      NaN

In [19]:
pd.merge(employees,salaries, on='employee_id',how='right')
# it shows employee_id on the bases salaries

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            4    Leo         IT   70000   8500
4            6    NaN        NaN   90000  12000