In [13]:
import numpy as np
import pandas as pd

Finding missing data

In [14]:
data = {
    'A': [1,2,np.nan,4,5],
    'B': [6,2,3,4,5],
    'C': [1,2,3,np.nan,np.nan],
    'D': [1,np.nan,np.nan,np.nan,5]
}

# np.nan means null value 
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [15]:
df.isna()
# for converting values into true and false
# for null = true and for value = false

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [16]:
df.isna().sum()
# for counting null values

A    1
B    0
C    2
D    3
dtype: int64

In [17]:
df.isna().any()
# for checking null value is present or not in each columns

A     True
B    False
C     True
D     True
dtype: bool

Removing missing data
<!-- this is working on bases of rows -->

In [18]:
df

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.dropna()
# to removing all the null values column wise 
# when u apply this whereever null values is presentt in rows so it gonna remove the whole row

     A  B    C    D
0  1.0  6  1.0  1.0

In [20]:
df

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna(thresh=3)
# u have atleast 3 non null values row wise

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Filling the missing data
<!-- in this we use coulmn wise approch and even in selection we use columns  -->

In [24]:
df

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.fillna(0)
# for filling null valuee = 0

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

# this func is use for applying specific values on null values in columns

     A  B      C      D
0  1.0  6    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [28]:
df

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [30]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  6  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0